spring.application.name=cospace

spring.datasource.url=jdbc:postgresql://localhost:5432/cospace_db
spring.datasource.username=your_username
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update