spring.application.name=cospace

spring.datasource.url=jdbc:postgresql://localhost:5432/cospace_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update