spring.application.name=cospace

spring.datasource.url=jdbc:postgresql://localhost:5432/cospace_db
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update